apiVersion: v1  
kind: Service                                 # Type of the kubernetes resource
metadata:
  name: fullstack-app-postgres                # Name of the Kubernetes resource
  labels:                                     # Labels that will be applied to the resource
    app: fullstack-app-postgres
spec:                             
  selector:
    app: fullstack-app-postgres               # Selects any Pod with labels `app=fullstack-app-postgres`
  ports: 
  - name: http
    port: 8080                                # exposes Application to 8080 port.
    targetPort: 8080